---
version: "3"

services:
  traefikRouter:
    image: traefik:latest
    depends_on:
      - dockerproxy
    ports:
      - 80:80
      - 443:443
      - 51820:51820/udp
    volumes:
      - ./config:/etc/traefik
    env_file:
      - ./tls.env.dec
    networks:
      - traefiknw
      - wireguardnw
      - nextcloudnw

  dockerproxy:
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    image: tecnativa/docker-socket-proxy
    labels:
      - traefik.enable=true
    networks:
      - traefiknw
    # ports:
    #   - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  wireguardnw:
    external: true
  nextcloudnw:
    external: true
  traefiknw:
    name: traefiknw
    enable_ipv6: true
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: fd6c:ec89:3749:6eaf:feed:bee0::/112
        - subnet: 172.19.0.0/24
