version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env.dec
    networks:
      - nextcloudnw

  nc_redis:
    image: redis:alpine
    restart: always
    volumes:
      - nc_redis:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nextcloudnw

  app:
    image: nextcloud
    restart: always
    # needed by apache
    hostname: nextcloud.zops.top
    labels:
      - traefik.enable=true
      - traefik.docker.network=nextcloudnw
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.service=nextcloud-svc
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=production
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.zops.top`)
      - traefik.http.services.nextcloud-svc.loadbalancer.server.port=80
      - traefik.http.services.nextcloud-svc.loadbalancer.passhostheader=true
      - traefik.http.services.nextcloud-svc.loadbalancer.sticky.cookie=true
      # Caldev Settings
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/
      # Middleware
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@docker, nextcloudHeaders@file, nextcloudRatelimiter@file"
    volumes:
      - nextcloud:/var/www/html:z
    env_file:
      - db.env.dec
      - redis.env.dec
      - nextcloud.env.dec
    depends_on:
      - db
      - nc_redis
    networks:
      - nextcloudnw

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - nc_redis
    networks:
      - nextcloudnw

networks:
  nextcloudnw:
    enable_ipv6: true
    name: nextcloudnw
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: fd6c:ec89:3749:6eaf:feed:bee2::/112
        - subnet: 172.19.2.0/24

volumes:
  db:
  nextcloud:
  nc_redis:
